added homework3
ol-nikolaieva/nikolaieva-Dec12 pull request #1
Opened 2022-12-25 11:05 UTC by ol-nikolaieva

2023-01-01 21:17 UTC, IIUPAMET requested changes

2023-01-01 21:17 UTC, IIUPAMET commented on src/ua/hillel/nikolaieva/homework3/CheckOddEven.java
> +        return "BYE!";
який сенс повертати "бай" якщо його тоді можна одразу вивести на екран

2023-01-01 21:17 UTC, IIUPAMET commented on src/ua/hillel/nikolaieva/homework3/CheckOddEven.java
> +    public static String getNumber (int number) {
назва метода не відповідає його дії

2023-01-04 19:07 UTC, ol-nikolaieva commented on src/ua/hillel/nikolaieva/homework3/CheckOddEven.java
> +    public static String getNumber (int number) {
дякую, виправила на той, що відповідає дійсності

2023-01-04 19:08 UTC, ol-nikolaieva commented on src/ua/hillel/nikolaieva/homework3/CheckOddEven.java
> +        return "BYE!";
бо не було інструкцій стосовно того, як саме має бути виведений цей стрінг. переписала метод без return

2023-01-15 16:02 UTC, merged